version: '2.1'

services:
  api:
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      STRAPI_URL: ${STRAPI_URL}
      SHOP_EMAIL_USER: ${SHOP_EMAIL_USER}
      SHOP_EMAIL_PASSWORD: ${SHOP_EMAIL_PASSWORD}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "1337:1337"

  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db:/data/db
    expose:
      - "27017"